spring:
  datasource:
      username: *
      password: *
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: *
      hikari:
        minimum-idle: 5
        connection-test-query: SELECT 1 FROM DUAL
        validation-timeout: 1000
        idle-timeout: 300000
        maximum-pool-size: 20
        destroy-method: shutdown

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      use_query_cache: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/

logging:
  config: classpath:logs/dev.xml

system:
  wx:
    app_id: *
    app_secret: *
  hp:
    app_id: *
    app_secret: *
